// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtmnrgypcvyjwiqtqppd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bW5yZ3lwY3Z5andpcXRxcHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzE2MzgsImV4cCI6MjA2MzM0NzYzOH0.6SMlC43rGdRvqAnMoenr1svbRyFfyc9fSvsJiN9K6Wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);