// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzjiaosnqpgsjsmpiodl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6amlhb3NucXBnc2pzbXBpb2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDQ4MjAsImV4cCI6MjA2Mzc4MDgyMH0.g-T0FYuTMdsWaU-ofx8QwFv3SK3fDjSFEl8tzIVPXyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);